# Copyright (c) 2026 Zhambyl Yermagambet
"""Build tool configurations with standard INI parsing and Ruff inheritance."""

import configparser
import io
from pathlib import Path

from pydantic import TypeAdapter

from baqylau_dev.models import ConfigurationPaths, ProjectProfile
from baqylau_dev.resources import POLICY_ROOT, policy_text

GENERATED = "# Generated by baqylau-dev. Change the shared policy or the host overlay.\n"
HOST_RUFF_RESOURCE = "packages/dev-tools/src/baqylau_dev/policy/ruff.toml"
ENCODING = "utf-8"


def ruff_configuration(root: Path, profile: ProjectProfile) -> str:
    """Use Ruff's own inheritance for common rules and host path settings.

    Returns:
        A thin configuration with one installed base resource.

    """
    base = str(POLICY_ROOT / "ruff.toml")
    overlay = ""
    if profile.profile == "host":
        base = HOST_RUFF_RESOURCE
        overlay = (root / "quality" / "ruff-host.toml").read_text(encoding=ENCODING)
    encoded = TypeAdapter(str).dump_json(base).decode(ENCODING)
    return f"{GENERATED}extend = {encoded}\n\n{overlay}\n{_ruff_paths(profile)}"


def mypy_configuration(root: Path, profile: ProjectProfile) -> str:
    """Assemble strict common settings and explicit host-only legacy sections.

    Returns:
        A complete mypy INI file.

    """
    parser = configparser.ConfigParser()
    parser.read_string(policy_text("mypy.ini"))
    if profile.profile == "host":
        parser.read(root / "quality" / "mypy-host.ini", encoding=ENCODING)
    else:
        search_paths = ", ".join(str(root / path) for path in profile.source_roots)
        parser.set("mypy", "mypy_path", search_paths)
    return _ini_text(parser)


def flake8_configuration(profile: ProjectProfile) -> str:
    """Keep WPS rules shared and supply the selected profile's environment paths.

    Returns:
        A complete Flake8 configuration.

    """
    parser = configparser.ConfigParser()
    parser.read_string(policy_text("flake8.ini"))
    parser.set("flake8", "exclude", ",\n".join(profile.design_excludes))
    return _ini_text(parser)


def configuration_paths(root: Path, profile: ProjectProfile) -> ConfigurationPaths:
    """Keep generated extension configuration local and host editor files stable.

    Returns:
        Tool paths for the selected profile.

    """
    directory = root if profile.profile == "host" else root / ".baqylau-dev"
    return ConfigurationPaths(
        ruff=directory / "ruff.toml", mypy=directory / "mypy.ini", flake8=directory / "setup.cfg",
    )


def expected_files(root: Path, profile: ProjectProfile) -> tuple[tuple[Path, str], ...]:
    """Use the same generated bytes for write and drift-check operations.

    Returns:
        Each generated tool file and its expected text.

    """
    paths = configuration_paths(root, profile)
    return (
        (paths.ruff, ruff_configuration(root, profile)), (paths.mypy, mypy_configuration(root, profile)),
        (paths.flake8, flake8_configuration(profile)),
    )


def _ini_text(parser: configparser.ConfigParser) -> str:
    stream = io.StringIO()
    parser.write(stream)
    lines = (line.rstrip() for line in stream.getvalue().splitlines())
    normalized = "\n".join(lines).rstrip()
    return f"{GENERATED}{normalized}\n"


def _ruff_paths(profile: ProjectProfile) -> str:
    template = policy_text("ruff-paths.toml")
    test_rule = next(
        line for line in template.splitlines() if line.startswith('"tests/**/*.py" =')
    )
    rows = []
    for root in profile.test_roots:
        encoded = TypeAdapter(str).dump_json(f"{root}/**/*.py").decode(ENCODING)
        rows.append(test_rule.replace('"tests/**/*.py"', encoded))
    return template.replace(test_rule, "\n".join(rows))
