# Copyright (c) 2026 Zhambyl Yermagambet
"""Prepare verified extension entries without executing feature code."""

from pathlib import Path

from baqylau_dev.class_declarations import CodeLocation
from baqylau_dev.import_checks import check_imports
from baqylau_dev.manifest_checks import BackendDeclaration, checked_backend
from baqylau_dev.models import ProjectProfile
from baqylau_dev.protocol_checks import verified_protocol_entries
from baqylau_dev.source_inventory import source_inventory

FACTORY_PROBE = ".baqylau-dev/extension_factory_check.py"


def check_extension(root: Path, profile: ProjectProfile) -> frozenset[CodeLocation]:
    """Validate package files, imports, and declared protocol method shapes.

    Returns:
        Exact source entries for the dead-code adapter.

    """
    modules = source_inventory(root, profile)
    backend = checked_backend(root, profile, modules)
    check_imports(root, modules)
    entries = verified_protocol_entries(backend, modules)
    _write_factory_probe(root, backend)
    return entries


def _write_factory_probe(root: Path, backend: BackendDeclaration) -> None:
    path = root / FACTORY_PROBE
    if not path.resolve().is_relative_to(root):
        message = "generated factory check escapes the project"
        raise ValueError(message)
    path.parent.mkdir(parents=True, exist_ok=True)
    name = backend.factory.name
    module_name = backend.module.name
    path.write_text(
        "# Generated by baqylau-dev. Do not edit.\n"
        "from baqylau_extension_api.contracts.plugin import ExtensionFactory\n"
        f"from {module_name} import {name}\n\n"
        f"extension_factory: ExtensionFactory = {name}\n",
        encoding="utf-8",
    )
