"""The harness protocol's messages and values — one module per concern.

Every gesture is one request dataclass in and one result dataclass out, and
every observation is a `RawEvent` in and a `TranslationResult` out, so a new
field on one operation never disturbs its neighbours. Nothing here knows a
concrete harness: these are the words every harness is described in.
"""

from harness.models.catalog import (
    CommandOption,
    EffortOption,
    HarnessCatalogSnapshot,
    ModelOption,
    QueryContext,
    RewindModeOption,
)
from harness.models.controls import (
    AnswerDecision,
    AnswerQuestion,
    ApplyRewind,
    AttachmentReference,
    Background,
    AutoNameSession,
    CloseSession,
    CommandResult,
    Compact,
    ConfirmationOutcome,
    ControlAcknowledgement,
    ControlContext,
    ControlName,
    ControlOutcome,
    ControlRequest,
    ControlResult,
    ControlTarget,
    DecidePlan,
    InterruptResult,
    MessageDeliveryResult,
    MessageDeliveryStatus,
    DurableTitleResult,
    Interrupt,
    OpenRewind,
    PlanChoice,
    PlanChoicesResult,
    ReadPlanChoices,
    RenameSession,
    RewindResult,
    SelectEffort,
    SelectModel,
    SendText,
    TitleWriteOutcome,
)
from domain.records import RecordedTranslationDecision
from harness.models.raw_events import (
    AUTOMATIC_TITLE_SOURCE_TYPE,
    CONTROL_SOURCE_TYPE,
    INTERRUPT_SOURCE_TYPE,
    LIVENESS_SOURCE_TYPE,
    OUTPUT_LOCATION_SOURCE_TYPE,
    RESUME_LIVENESS_SOURCE_TYPE,
    RESUME_SOURCE_TYPE,
    TITLE_SOURCE_TYPE,
    RawEvent,
    RawEventAudit,
    RawEventSourceContext,
    TranslationError,
    TranslationResult,
    UnknownRawEvent,
    canonical_event,
    output_location_raw_event,
    plan_resolution_phase,
    session_run_finished_event,
    session_run_started_events,
)
from harness.models.hooks import HarnessHookRequest, HarnessHookResponse
from harness.models.telemetry import (
    TELEMETRY_KIND_HEADER,
    TELEMETRY_MAX,
    HarnessTelemetryRequest,
    HarnessTelemetryResponse,
    TelemetryContext,
)
from harness.models.info import HarnessInfo
from harness.models.interrupts import InterruptRegistry
from harness.models.launch import (
    HarnessLaunchPlan,
    LaunchRejected,
    LaunchRequest,
    LaunchResult,
    LaunchStatus,
)
from harness.models.probe import TerminalInputState, TerminalSessionState
from harness.models.session import Session
from harness.models.usage import (
    AccountUsageSnapshot,
    UsageBlock,
    UsageRow,
    UsageWindow,
    UsageWindowSample,
    UsageWindowScope,
)

__all__ = [
    "AccountUsageSnapshot",
    "AnswerDecision",
    "AnswerQuestion",
    "ApplyRewind",
    "AttachmentReference",
    "AutoNameSession",
    "AUTOMATIC_TITLE_SOURCE_TYPE",
    "CloseSession",
    "CommandOption",
    "CommandResult",
    "Compact",
    "ConfirmationOutcome",
    "ControlAcknowledgement",
    "ControlContext",
    "ControlName",
    "ControlOutcome",
    "ControlRequest",
    "ControlResult",
    "ControlTarget",
    "CONTROL_SOURCE_TYPE",
    "DecidePlan",
    "InterruptResult",
    "MessageDeliveryResult",
    "MessageDeliveryStatus",
    "DurableTitleResult",
    "EffortOption",
    "HarnessCatalogSnapshot",
    "HarnessHookRequest",
    "HarnessHookResponse",
    "HarnessInfo",
    "InterruptRegistry",
    "HarnessTelemetryRequest",
    "HarnessTelemetryResponse",
    "HarnessLaunchPlan",
    "INTERRUPT_SOURCE_TYPE",
    "Background",
    "Interrupt",
    "LIVENESS_SOURCE_TYPE",
    "TELEMETRY_KIND_HEADER",
    "TELEMETRY_MAX",
    "LaunchRejected",
    "LaunchRequest",
    "LaunchResult",
    "LaunchStatus",
    "ModelOption",
    "OUTPUT_LOCATION_SOURCE_TYPE",
    "RESUME_LIVENESS_SOURCE_TYPE",
    "RESUME_SOURCE_TYPE",
    "TITLE_SOURCE_TYPE",
    "OpenRewind",
    "PlanChoice",
    "PlanChoicesResult",
    "QueryContext",
    "RawEvent",
    "RawEventAudit",
    "RawEventSourceContext",
    "ReadPlanChoices",
    "RecordedTranslationDecision",
    "RenameSession",
    "RewindModeOption",
    "RewindResult",
    "SelectEffort",
    "SelectModel",
    "SendText",
    "Session",
    "TerminalInputState",
    "TelemetryContext",
    "TerminalSessionState",
    "TitleWriteOutcome",
    "TranslationError",
    "TranslationResult",
    "UnknownRawEvent",
    "UsageBlock",
    "UsageRow",
    "UsageWindow",
    "UsageWindowSample",
    "UsageWindowScope",
    "canonical_event",
    "output_location_raw_event",
    "plan_resolution_phase",
    "session_run_finished_event",
    "session_run_started_events",
]
