# Copyright (c) 2026 Zhambyl Yermagambet
"""Name the current protocol methods inside the process adapter."""

LOAD = "worker.load"
ACTIVATE = "extension.activate"
DEACTIVATE = "extension.deactivate"
SOURCES_DESCRIBE = "extension.sources.describe"
SOURCES_READ = "extension.sources.read"
SOURCES_RELEASE = "extension.sources.release"
TRANSLATE = "extension.translate"
RAW_TRANSFORM = "extension.raw.transform"
CANONICAL_TRANSFORM = "extension.canonical.transform"
PROJECT = "extension.project"
PROJECT_SELECT = "extension.project.select_records"
PROJECTION_TRANSFORM = "extension.projection.transform"
TERMINAL_PRESENT = "extension.terminal.present"
QUERY = "extension.query"
COMMAND_EXECUTE = "extension.command.execute"
COMMAND_CANCEL = "extension.command.cancel"
COMMAND_RECONCILE = "extension.command.reconcile"
MIGRATE_SETTINGS = "extension.migrate.settings"
MIGRATE_RECORDS = "extension.migrate.records"
OBSERVE = "extension.observe"
OBSERVE_CANCEL = "extension.observe.cancel"
OBSERVE_RECONCILE = "extension.observe.reconcile"
DIRECTORY = "host.directory"
SERVICE_RESOLVE = "host.service.resolve"
SERVICE_QUERY = "host.service.query"
